# === Build Stage ===
FROM oven/bun:slim

WORKDIR /app

# Copy dependencies files
COPY package.json vite.config.js ./
COPY index.html ./
COPY public ./public
COPY src ./src
COPY .env.local ./
# Install dependencies and build the app
RUN bun install && bun run build


# Expose the port
EXPOSE 3000
# Serve the built app
CMD ["bun", "vite", "preview"]