services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5000:3000"
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5001:3001"