version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    volumes:
      # Mount any necessary config files or data
      - ./server/private_encrypted.key:/src/private_encrypted.key:ro
      - ./server/public.key:/src/public.key:ro
