# === Build Stage ===
FROM oven/bun:slim

WORKDIR /app

# Copy dependencies files
COPY package.json vite.config.js ./
COPY index.html ./
COPY public ./public
COPY src ./src
COPY .env ./
# Install dependencies and build the app
RUN bun install && bun run build


# Expose the port
EXPOSE 3000
RUN bun install serve
# Serve the built app
CMD ["bun", "run", "serve", "-s", "dist", "-l", "3000"]