services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5000:3000"
    env_file:
      - .env

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5001:3001"
    env_file:
      - ./server/.env
    # volumes:
    #   - ./server/private_encrypted.key:/src/private_encrypted.key:ro
    #   - ./server/public.key:/src/public.key:ro
